apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: szxq1g993-python 
  janus-idp.io/tekton: szxq1g993-python
  backstage.io/kubernetes-id: szxq1g993-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: szxq1g993-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml