apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: szxq1g993-python
  janus-idp.io/tekton: szxq1g993-python
  backstage.io/kubernetes-id: szxq1g993-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: szxq1g993-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
