apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: szxq1g993-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: szxq1g993-python 
  name: szxq1g993-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: szxq1g993-python 
